# Basic Metadata
title: CSE 455 Final
description: Personal Website
theme: just-the-docs

url: https://junwang0510.github.io

# Aux Links
aux_links:
  # TODO: Change code's path
  "Code":
  - "https://github.com/junwang0510/CSE455Final/tree/main/assets/Code"
  "Video":
  - "https://youtu.be/sMYo5r__L48"
aux_links_new_tab: true

# Buttons and Labels
enable_copy_code_button: true
callouts:
  warning:
    color: red
  highlight:
    color: yellow
  note:
    color: purple
  important:
    color: blue
  new:
    color: green

# Footer Content
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; 2023 Robin Wang, Jun Wang"